### ISSUE TITLE
Add class: TheMan

### ISSUE THREAD

**Issue by maurges** [tsu-trpo/puckmun#5]
(Это пэкмэн, но мы не забываем об авторских правах)
Унаследован от AnimateObject .
Должен содержать очередь движений (не обязательно queue), из которой по tick() достаётся и отдаётся текущее направление.

**Comment by alex8h** [comment]
Никит, зачем тут очередь движений? При движении он же запоминает  только одно движение, если оно не выполнимо, то доходит до стенки и стоит...

**Comment by maurges** [comment]
Ты почти права. В оригинальном пэкмене можно нажать кнопку чуть заранее поворота, и пэкмэн повернёт, дойдя до стены. Так что вместо очереди хватит двух действий: текущего и запланированного.
